export default  {
	rive:{
		text:"rive",
		decoration:"text-slate-600",
		url:"https://rive.app",
		icon:"rive",
	},
	astro:{
		text:"astro",
		decoration:"text-orange-600",
		url:"https://astro.build",
		icon:"vscode-icons:file-type-astro",
	},
	powershell: {
		text: "powershell",
		decoration: "text-sky-400",
		url: "https://docs.microsoft.com/en-us/powershell/",
		icon: `vscode-icons:file-type-powershell`
	},
	svg: {
		text: "svg",
		decoration: "text-yellow-500",
		url: "https://www.w3.org/TR/SVG2/",
		icon: `logos:svg`,
	},
	figma: {
		text: "Figma",
		decoration: "text-purple-300",
		url: "https://www.figma.com/",
		icon: "logos:figma",
	},
	framer: {
		text: "framer motion",
		decoration: "text-slate-400",
		url: "https://www.framer.com/motion/",
		icon: "radix-icons:framer-logo",
	},
	git: {
		text: "git",
		decoration: "text-red-400",
		url: "https://git-scm.com/",
		icon: "vscode-icons:file-type-git",
	},
	vscode: {
		text: "git",
		decoration: "text-red-400",
		url: "https://git-scm.com/",
		icon: "git-scm",
	},
	github: {
		text: "github",
		decoration: "text-slate-400",
		url: "https://github.com/",
		icon: "codicon:github",
	},
	vim: {
		text: "vim",
		decoration: "text-slate-400",
		url: "https://www.vim.org/",
		icon: "logos:vim",
	},
	neovim: {
		text: "neovim",
		decoration: "text-slate-500",
		url: "https://neovim.io/",
		icon: "simple-icons:neovim",
	},
	react: {
		text: "react",
		decoration: "text-slate-500",
		url: "https://reactjs.org/",
		icon: `logos:react`,
	},
	vue: {
		text: "vue",
		decoration: "text-slate-500",
		url: "https://v3.vuejs.org/",
		icon: "vscode-icons:file-type-vue",
	},
	node: {
		text: "node",
		decoration: "text-slate-500",
		url: "https://nodejs.dev/",
		icon: "logos:nodejs-icon",
	},
	html: {
		text: "HTML",
		decoration: "text-orange-400",
		url: "https://www.w3schools.com/html/",
		icon: "vscode-icons:file-type-html",
	},
	stencil: {
		text: "stencil_js",
		decoration: "text-gray-200",
		url: "https://stenciljs.com/",
		icon: "vscode-icons:file-type-stencil",
	},
	pug: {
		text: "Pugjs",
		decoration: "text-stone-400",
		url: "https://www.w3schools.com/css/",
		icon: "logos:pug",
	},
	css: {
		text: "CSS",
		decoration: "text-blue-400",
		url: "https://www.w3schools.com/css/",
		icon: "vscode-icons:file-type-css",
	},
	tailwindcss: {
		text: "tailwindcss",
		decoration: "text-teal-400",
		url: "https://tailwindcss.com",
		icon: "logos:tailwindcss-icon",
	},
	javascript: {
		text: "javascript",
		decoration: "text-amber-400",
		url: "https://www.javascript.com/",
		icon: "vscode-icons:file-type-js",
	},
	typescript: {
		text: "typescript",
		decoration: "text-blue-400",
		url: "https://www.typescriptlang.org/",
		icon: "vscode-icons:file-type-typescript-official",
	},
	rust:{
		text:"rust",
		decoration: "text-stone-600",
		url: "https://www.rust-lang.org/",
		icon:"vscode-icons:file-type-rust",
	},
	python: {
		text: "python",
		decoration: "text-yellow-400",
		url: "https://www.python.org/",
		icon: "vscode-icons:file-type-python",
	},
	svelte: {
		text: "svelte",
		decoration: "text-orange-400",
		url: "https://svelte.dev/",
		icon: "vscode-icons:file-type-svelte",
	},
	sveltekit: {
		text: "sveltekit",
		decoration: "text-orange-400",
		url: "https://kit.svelte.dev/",
		icon: "vscode-icons:file-type-svelte",
	},
	alpine: {
		text: "alpinejs",
		decoration: "text-alpine",
		url: "https://alpinejs.dev",
		icon: "alpine",
	},
	dart: {
		text: "dart",
		decoration: "text-cyan-400",
		url: "https://dart.dev/",
		icon: "logos:dart",
	},
	flutter: {
		text: "flutter",
		decoration: "text-cyan-500",
		url: "https://flutter.dev/",
		icon: "vscode-icons:file-type-flutter",
	},
	mongodb: {
		text: "MongoDB",
		decoration: "text-lime-500",
		url: "https://www.mongodb.com/",
		icon: "vscode-icons:file-type-mongo",
	},
	firebase: {
		text: "firebase",
		decoration: "text-yellow-500",
		url: "https://firebase.google.com",
		icon: "vscode-icons:file-type-firebase",
	},
};
